version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    # ↓これらの環境変数は、コンテナ起動時に使用する。
    # dockerimageですでに指定された環境定数名なので、カスタマイズはできない
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
